import { defineConfig } from 'vitest/config'
import { fileURLToPath, URL } from 'node:url'

export default defineConfig({
  resolve: {
    alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) },
  },
  test: {
    environment: 'jsdom',
    exclude: ['e2e/**', 'node_modules/**', 'dist/**'],
    coverage: {
      provider: 'istanbul',
      reporter: ['text', 'json-summary'],
      // The whole application, not a seven-file allowlist. The previous list
      // reported 97% over 208 statements while every component sat outside the
      // denominator, which is how a confirmation dialog that never closed
      // passed a green coverage gate.
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/app/routeTree.gen.ts',
        'src/main.tsx',
        'src/vite-env.d.ts',
        'src/i18n/i18next.d.ts',
        // Vendored registry primitives are owned code but not ours to test:
        // they are regenerated by `shadcn add` and covered upstream.
        'src/shared/components/ui/**',
        'src/shared/testing/**',
        // Route files are three-line declarations that mount a feature; the
        // tree they build is generated and the Playwright suite walks it.
        'src/app/routes/**',
        'src/app/router.ts',
      ],
      // Set to what the tree actually reaches, so the gate ratchets instead of
      // describing an aspiration. Statements, functions and lines clear the 80%
      // baseline; branches sit lower and honestly so — much of the remainder is
      // the per-field `available === false` fallbacks the console renders for
      // facts a device did not observe, and covering every permutation of those
      // is a combinatorial exercise rather than a contract. Raise these numbers
      // when work covers more; never lower them to make a change pass.
      thresholds: {
        statements: 82,
        branches: 73,
        functions: 80,
        lines: 85,
      },
    },
  },
})
