use super::*;
use crate::reconciler::systemd::mock::MockUnitControl;
use micad_settings::Settings;
use std::path::Path;

/// Fixture: a quadlet dir and a generator dir, both empty.
fn dirs() -> (tempfile::TempDir, PathBuf, PathBuf) {
    let tmp = tempfile::tempdir().expect("tempdir");
    let quadlet = tmp.path().join("quadlet");
    let generator = tmp.path().join("generator");
    std::fs::create_dir_all(&quadlet).expect("quadlet dir");
    std::fs::create_dir_all(&generator).expect("generator dir");
    (tmp, quadlet, generator)
}

fn settings(enabled: bool) -> Settings {
    let mut s = Settings::default();
    s.container.enabled = enabled;
    s
}

/// A unit file as Quadlet writes one: the ExecStart names the podman this
/// image installs, which is how the reconciler recognises it.
fn write_generated(generator: &Path, name: &str) {
    std::fs::write(
        generator.join(name),
        "# Automatically generated by quadlet-generator\n\
         [Service]\nExecStart=/usr/bin/podman run --name x docker.io/library/busybox\n",
    )
    .expect("write generated unit");
}

#[tokio::test]
async fn enabling_mounts_the_bind_and_then_reloads() {
    let (_tmp, quadlet, generator) = dirs();
    let control = MockUnitControl::new("inactive", "disabled");
    let r = ContainerReconciler::new(quadlet, generator, control);

    r.apply(&settings(true)).await.expect("apply");

    // The order is the assertion, not merely the set: a reload before the
    // mount reads the image's empty directory and generates nothing, and
    // every individual call still succeeds.
    let calls = r.control.calls();
    let mount_at = calls
        .iter()
        .position(|c| c == &format!("start {QUADLET_MOUNT_UNIT}"))
        .expect("the mount is started");
    let reload_at = calls
        .iter()
        .position(|c| c == "daemon-reload -")
        .expect("generators are re-run");
    assert!(
        mount_at < reload_at,
        "daemon-reload ran before the mount, so Quadlet would have parsed the image's empty directory: {calls:?}"
    );
}

#[tokio::test]
async fn disabling_stops_generated_units_before_unmounting() {
    let (_tmp, quadlet, generator) = dirs();
    write_generated(&generator, "app.service");
    let control = MockUnitControl::new("inactive", "disabled");
    control.set_active_state("app.service", "active");
    control.set_active_state(QUADLET_MOUNT_UNIT, "active");
    let r = ContainerReconciler::new(quadlet, generator, control);

    let state = r.apply(&settings(false)).await.expect("apply");

    let calls = r.control.calls();
    let app_at = calls
        .iter()
        .position(|c| c == "stop app.service")
        .expect("the container unit is stopped");
    let mount_at = calls
        .iter()
        .position(|c| c == &format!("stop {QUADLET_MOUNT_UNIT}"))
        .expect("the mount is stopped");
    assert!(
        app_at < mount_at,
        "the bind was unmounted before the container was stopped, which orphans a running root container behind a unit name that no longer resolves: {calls:?}"
    );
    assert_eq!(
        state["stoppedUnits"],
        serde_json::json!(["app.service"]),
        "what was stopped has to be reportable, or an operator cannot tell a switch that acted from one that found nothing"
    );
}

#[tokio::test]
async fn a_generated_unit_is_recognised_by_content_not_by_name() {
    let (_tmp, quadlet, generator) = dirs();
    // Quadlet's own name mapping has cases this reconciler deliberately does
    // not reimplement: a `.pod` file becomes `<name>-pod.service`. Both names
    // below are ones a filename-based rule would have to know in advance.
    write_generated(&generator, "web-pod.service");
    write_generated(&generator, "db-volume.service");
    // Not Quadlet's: a stock unit that happens to live in the generator dir.
    std::fs::write(
        generator.join("systemd-fstab-generated.service"),
        "[Service]\nExecStart=/bin/true\n",
    )
    .expect("write foreign unit");

    let control = MockUnitControl::new("inactive", "disabled");
    for u in ["web-pod.service", "db-volume.service"] {
        control.set_active_state(u, "active");
    }
    control.set_active_state(QUADLET_MOUNT_UNIT, "active");
    let r = ContainerReconciler::new(quadlet, generator, control);

    let state = r.apply(&settings(false)).await.expect("apply");

    assert_eq!(
        state["stoppedUnits"],
        serde_json::json!(["db-volume.service", "web-pod.service"]),
        "both Quadlet units must be stopped whatever their name suffix"
    );
    let calls = r.control.calls();
    assert!(
        !calls.iter().any(|c| c.contains("systemd-fstab-generated")),
        "a unit this reconciler did not generate was touched: {calls:?}"
    );
}

#[tokio::test]
async fn off_and_nothing_to_run_are_distinguishable() {
    let (_tmp, quadlet, generator) = dirs();
    std::fs::write(quadlet.join("app.container"), "[Container]\nImage=x\n").expect("write");
    let control = MockUnitControl::new("inactive", "disabled");
    let r = ContainerReconciler::new(quadlet.clone(), generator.clone(), control);

    let off = r.apply(&settings(false)).await.expect("apply off");
    assert_eq!(
        off["quadletFiles"],
        serde_json::json!([]),
        "with the bind down the directory is the image's, so reporting STATE's files would describe something not visible to Quadlet"
    );

    let on = r.apply(&settings(true)).await.expect("apply on");
    assert_eq!(
        on["quadletFiles"],
        serde_json::json!(["app.container"]),
        "with the bind up an operator has to be able to see that a file exists but produced no unit"
    );
}

#[tokio::test]
async fn enabling_twice_does_not_re_enable_an_already_enabled_mount() {
    let (_tmp, quadlet, generator) = dirs();
    let control = MockUnitControl::new("inactive", "disabled");
    control.set_unit_file_state(QUADLET_MOUNT_UNIT, "enabled-runtime");
    control.set_active_state(QUADLET_MOUNT_UNIT, "active");
    let r = ContainerReconciler::new(quadlet, generator, control);

    r.apply(&settings(true)).await.expect("apply");

    let calls = r.control.calls();
    assert!(
        !calls.iter().any(|c| c.starts_with("enable ")),
        "an already-enabled mount was enabled again: {calls:?}"
    );
    assert!(
        !calls.iter().any(|c| c.starts_with("start ")),
        "an already-mounted bind was started again: {calls:?}"
    );
    assert!(
        calls.iter().any(|c| c == "daemon-reload -"),
        "the reload is NOT conditional on the mount having changed: micad reconciles on every start, and a .container file added while the bind was already up becomes a unit only when generators re-run: {calls:?}"
    );
}

#[tokio::test]
async fn enabling_starts_the_units_quadlet_generated() {
    // THE GAP THIS TEST EXISTS FOR. A daemon-reload makes Quadlet write the
    // unit and its .wants symlink; systemd does not start units that become
    // wanted during a reload, because the target that wants them was reached
    // long before. Without an explicit start the switch turns on an engine
    // that runs nothing, and every unit-level observation says it worked.
    let (_tmp, quadlet, generator) = dirs();
    write_generated(&generator, "probe.service");
    let control = MockUnitControl::new("inactive", "disabled");
    let r = ContainerReconciler::new(quadlet, generator, control);

    let state = r.apply(&settings(true)).await.expect("apply");

    let calls = r.control.calls();
    let reload_at = calls
        .iter()
        .position(|c| c == "daemon-reload -")
        .expect("generators are re-run");
    let start_at = calls
        .iter()
        .position(|c| c == "start probe.service")
        .expect("the generated unit is started");
    assert!(
        reload_at < start_at,
        "the unit was started before the reload that generates it: {calls:?}"
    );
    assert_eq!(
        state["startedUnits"],
        serde_json::json!(["probe.service"]),
        "what was started has to be reportable, or 'the switch is on' and 'something is running' are indistinguishable"
    );
}

#[tokio::test]
async fn an_already_running_container_is_not_restarted() {
    let (_tmp, quadlet, generator) = dirs();
    write_generated(&generator, "probe.service");
    let control = MockUnitControl::new("inactive", "disabled");
    control.set_active_state("probe.service", "active");
    control.set_active_state(QUADLET_MOUNT_UNIT, "active");
    control.set_unit_file_state(QUADLET_MOUNT_UNIT, "enabled-runtime");
    let r = ContainerReconciler::new(quadlet, generator, control);

    r.apply(&settings(true)).await.expect("apply");

    let calls = r.control.calls();
    assert!(
        !calls.iter().any(|c| c == "start probe.service"),
        "a running container was started again, which for a Restart=always unit is a needless outage: {calls:?}"
    );
}
