/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SystemRouteImport } from './routes/system'
import { Route as NetworkNameRouteImport } from './routes/network_.$name'
import { Route as ServicesServiceRouteImport } from './routes/services_.$service'
import { Route as SystemUiRouteImport } from './routes/system_.ui'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkNameRoute = NetworkNameRouteImport.update({
  id: '/network_/$name',
  path: '/network/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services_/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUiRoute = SystemUiRouteImport.update({
  id: '/system_/ui',
  path: '/system/ui',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/applications': typeof ApplicationsRoute
  '/network': typeof NetworkRoute
  '/services': typeof ServicesRoute
  '/system': typeof SystemRoute
  '/network/$name': typeof NetworkNameRoute
  '/services/$service': typeof ServicesServiceRoute
  '/system/ui': typeof SystemUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/applications': typeof ApplicationsRoute
  '/network': typeof NetworkRoute
  '/services': typeof ServicesRoute
  '/system': typeof SystemRoute
  '/network/$name': typeof NetworkNameRoute
  '/services/$service': typeof ServicesServiceRoute
  '/system/ui': typeof SystemUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/applications': typeof ApplicationsRoute
  '/network': typeof NetworkRoute
  '/services': typeof ServicesRoute
  '/system': typeof SystemRoute
  '/network_/$name': typeof NetworkNameRoute
  '/services_/$service': typeof ServicesServiceRoute
  '/system_/ui': typeof SystemUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/applications'
    | '/network'
    | '/services'
    | '/system'
    | '/network/$name'
    | '/services/$service'
    | '/system/ui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/applications'
    | '/network'
    | '/services'
    | '/system'
    | '/network/$name'
    | '/services/$service'
    | '/system/ui'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/applications'
    | '/network'
    | '/services'
    | '/system'
    | '/network_/$name'
    | '/services_/$service'
    | '/system_/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ApplicationsRoute: typeof ApplicationsRoute
  NetworkRoute: typeof NetworkRoute
  ServicesRoute: typeof ServicesRoute
  SystemRoute: typeof SystemRoute
  NetworkNameRoute: typeof NetworkNameRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  SystemUiRoute: typeof SystemUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network_/$name': {
      id: '/network_/$name'
      path: '/network/$name'
      fullPath: '/network/$name'
      preLoaderRoute: typeof NetworkNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$service': {
      id: '/services_/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system_/ui': {
      id: '/system_/ui'
      path: '/system/ui'
      fullPath: '/system/ui'
      preLoaderRoute: typeof SystemUiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ApplicationsRoute: ApplicationsRoute,
  NetworkRoute: NetworkRoute,
  ServicesRoute: ServicesRoute,
  SystemRoute: SystemRoute,
  NetworkNameRoute: NetworkNameRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  SystemUiRoute: SystemUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
