/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AccessRouteImport } from './app/routes/access'
import { Route as DiagnosticsRouteImport } from './app/routes/diagnostics'
import { Route as NetworkRouteImport } from './app/routes/network'
import { Route as NetworkStatusRouteImport } from './app/routes/network-status'
import { Route as ServicesRouteImport } from './app/routes/services'
import { Route as StorageRouteImport } from './app/routes/storage'
import { Route as SystemRouteImport } from './app/routes/system'
import { Route as SystemInformationRouteImport } from './app/routes/system-information'
import { Route as TimeRouteImport } from './app/routes/time'
import { Route as SystemUiRouteImport } from './app/routes/system_.ui'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkStatusRoute = NetworkStatusRouteImport.update({
  id: '/network-status',
  path: '/network-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemInformationRoute = SystemInformationRouteImport.update({
  id: '/system-information',
  path: '/system-information',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUiRoute = SystemUiRouteImport.update({
  id: '/system_/ui',
  path: '/system/ui',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/network': typeof NetworkRoute
  '/network-status': typeof NetworkStatusRoute
  '/services': typeof ServicesRoute
  '/storage': typeof StorageRoute
  '/system': typeof SystemRoute
  '/system-information': typeof SystemInformationRoute
  '/time': typeof TimeRoute
  '/system/ui': typeof SystemUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/network': typeof NetworkRoute
  '/network-status': typeof NetworkStatusRoute
  '/services': typeof ServicesRoute
  '/storage': typeof StorageRoute
  '/system': typeof SystemRoute
  '/system-information': typeof SystemInformationRoute
  '/time': typeof TimeRoute
  '/system/ui': typeof SystemUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/network': typeof NetworkRoute
  '/network-status': typeof NetworkStatusRoute
  '/services': typeof ServicesRoute
  '/storage': typeof StorageRoute
  '/system': typeof SystemRoute
  '/system-information': typeof SystemInformationRoute
  '/time': typeof TimeRoute
  '/system_/ui': typeof SystemUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/diagnostics'
    | '/network'
    | '/network-status'
    | '/services'
    | '/storage'
    | '/system'
    | '/system-information'
    | '/time'
    | '/system/ui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/diagnostics'
    | '/network'
    | '/network-status'
    | '/services'
    | '/storage'
    | '/system'
    | '/system-information'
    | '/time'
    | '/system/ui'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/diagnostics'
    | '/network'
    | '/network-status'
    | '/services'
    | '/storage'
    | '/system'
    | '/system-information'
    | '/time'
    | '/system_/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  NetworkRoute: typeof NetworkRoute
  NetworkStatusRoute: typeof NetworkStatusRoute
  ServicesRoute: typeof ServicesRoute
  StorageRoute: typeof StorageRoute
  SystemRoute: typeof SystemRoute
  SystemInformationRoute: typeof SystemInformationRoute
  TimeRoute: typeof TimeRoute
  SystemUiRoute: typeof SystemUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-status': {
      id: '/network-status'
      path: '/network-status'
      fullPath: '/network-status'
      preLoaderRoute: typeof NetworkStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-information': {
      id: '/system-information'
      path: '/system-information'
      fullPath: '/system-information'
      preLoaderRoute: typeof SystemInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system_/ui': {
      id: '/system_/ui'
      path: '/system/ui'
      fullPath: '/system/ui'
      preLoaderRoute: typeof SystemUiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  NetworkRoute: NetworkRoute,
  NetworkStatusRoute: NetworkStatusRoute,
  ServicesRoute: ServicesRoute,
  StorageRoute: StorageRoute,
  SystemRoute: SystemRoute,
  SystemInformationRoute: SystemInformationRoute,
  TimeRoute: TimeRoute,
  SystemUiRoute: SystemUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
