/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AccessRouteImport } from './app/routes/access'
import { Route as NetworkRouteImport } from './app/routes/network'
import { Route as ServicesRouteImport } from './app/routes/services'
import { Route as SystemRouteImport } from './app/routes/system'
import { Route as SystemUiRouteImport } from './app/routes/system_.ui'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUiRoute = SystemUiRouteImport.update({
  id: '/system_/ui',
  path: '/system/ui',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/network': typeof NetworkRoute
  '/services': typeof ServicesRoute
  '/system': typeof SystemRoute
  '/system/ui': typeof SystemUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/network': typeof NetworkRoute
  '/services': typeof ServicesRoute
  '/system': typeof SystemRoute
  '/system/ui': typeof SystemUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/network': typeof NetworkRoute
  '/services': typeof ServicesRoute
  '/system': typeof SystemRoute
  '/system_/ui': typeof SystemUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/access' | '/network' | '/services' | '/system' | '/system/ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access' | '/network' | '/services' | '/system' | '/system/ui'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/network'
    | '/services'
    | '/system'
    | '/system_/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  NetworkRoute: typeof NetworkRoute
  ServicesRoute: typeof ServicesRoute
  SystemRoute: typeof SystemRoute
  SystemUiRoute: typeof SystemUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system_/ui': {
      id: '/system_/ui'
      path: '/system/ui'
      fullPath: '/system/ui'
      preLoaderRoute: typeof SystemUiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  NetworkRoute: NetworkRoute,
  ServicesRoute: ServicesRoute,
  SystemRoute: SystemRoute,
  SystemUiRoute: SystemUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
